import {
  AlignEndHorizontal,
  AlignVerticalJustifyEnd,
  ArrowDownUp,
  FileDigit,
  Home,
  ListOrderedIcon,
  Menu,
  Settings,
  TimerOffIcon
} from "lucide-react"

import { MenuListType } from "./Interface/MenuList.js"

export const MenuList: MenuListType[] = [
  {
    key: "1",
    title: "Home",
    pathTitle: "Home",
    icon: <Home className=" h-5 w-5" />,
    path: "/admin",
    items: [],
  },
  // {
  //   key: "",
  //   title: "Sales",
  //   pathTitle: "Sales",
  //   icon: <ArrowDownUp className=" h-5 w-5" />,
  //   path: "",
  //   items: [
  //     {
  //       key: "",
  //       title: "Sales1",
  //       pathTitle: "Division",
  //       icon: <ArrowDownUp className=" h-5 w-5" />,
  //       path: "/admin/sales/sales1",
  //     },
  //   ],
  // },
  {
    key: "2",
    title: "Menus",
    pathTitle: "Menus",
    icon: <Menu className=" h-5 w-5" />,
    path: "/admin/menus",
    items: [],
  },
  // {
  //   key: "",
  //   title: "Live Orders",
  //   pathTitle: "Live Orders",
  //   icon: <ArrowDownUp className=" h-5 w-5" />,
  //   path: "/Live Orders",
  //   items: [],
  // },
  // {
  //   key: "",
  //   title: "Team",
  //   pathTitle: "Team",
  //   icon: <Menu className=" h-5 w-5" />,
  //   path: "/team",
  //   items: [],
  // },
  // {
  //   key: "",
  //   title: "Invoices",
  //   pathTitle: "Invoices",
  //   icon: <ArrowDownUp className=" h-5 w-5" />,
  //   path: "/Team",
  //   items: [],
  // },
  // {
  //   key: "",
  //   title: "Marketer",
  //   pathTitle: "Marketer",
  //   icon: <Menu className=" h-5 w-5" />,
  //   path: "/Marketer",
  //   items: [],
  // },
  // {
  //   key: "",
  //   title: "Help",
  //   pathTitle: "Help",
  //   icon: <ArrowDownUp className=" h-5 w-5" />,
  //   path: "/Help",
  //   items: [],
  // },

  {
    key: "3",
    title: "Settings",
    pathTitle: "Settings",
    icon: <Settings className=" h-5 w-5" />,
    path: "",
    items: [
      {
        key: "11",
        title: "Profile",
        pathTitle: "Profile",
        icon: <ArrowDownUp className=" h-5 w-5" />,
        path: "/admin/settings/profile",
      },
      {
        key: "12",
        title: "Opening and Closing Time",
        pathTitle: "open-close-time",
        icon: <TimerOffIcon className=" h-5 w-5" />,
        path: "/admin/settings/open-close-time",
      },
      {
        key: "13",
        title: "Inactive Menu",
        pathTitle: "inactive-menu",
        icon: <AlignVerticalJustifyEnd className=" h-5 w-5" />,
        path: "/admin/settings/inactive-menu",
      },
      {
        key: "14",
        title: "Inactive Item",
        pathTitle: "inactive-item",
        icon: <AlignEndHorizontal className=" h-5 w-5" />,
        path: "/admin/settings/inactive-item",
      },
      {
        key: "14",
        title: "Inactive Extra Item",
        pathTitle: "inactive-item",
        icon: <AlignEndHorizontal className=" h-5 w-5" />,
        path: "/admin/settings/inactive-extra-item",
      },
    ],
  },
  {
    key: "4",
    title: "Extra Item",
    pathTitle: "Extra Item",
    icon: <FileDigit className=" h-5 w-5" />,
    path: "/admin/extra-item",
    items: [],
  },
  {
    key: "5",
    title: "Order",
    pathTitle: "order",
    icon: <ListOrderedIcon className=" h-5 w-5" />,
    path: "/admin/order",
    items: [],
  },
]
